# Generated by Django 5.2.12 on 2026-04-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cf_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
